### ISSUE TITLE
我把nginx 删除了改用它,有个问题

### ISSUE THREAD

**Issue by ghost** [liberal-boy/tls-shunt-proxy#3]
用acme 签发好的证书似乎 是有问题 .(即把managedcert 设置为false,用以前已经签发好的证书失败)
小软件很不错,感谢作者辛苦付出,就是更新的有点太频繁了,可能是刚开始吧

**Comment by liberal-boy** [comment]
managed cert 顾名思义是管理证书，包括签发，续签，缓存等，关闭之后他缓存的证书当然也就用不了了，必须自己指定证书。

**Comment by hedsbj** [comment]
就是指定自己的证书不成功.那证书是以前用acme 手工申请 的,原来用在nginx上都是ok的

**Comment by liberal-boy** [comment]
请详细描述问题以及提供日志

**Comment by hedsbj** [comment]
在运行的时候显示如下信息

● tls-shunt-proxy.service - TLS Shunt Proxy Service
   Loaded: loaded (/etc/systemd/system/tls-shunt-proxy.service; disabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Tue 2020-04-07 13:50:53 CST; 1h 43min ago
     Docs: https://github.com/liberal-boy/tls-shunt-proxy/blob/master/README.md
  Process: 7266 ExecStart=/usr/local/bin/tls-shunt-proxy -config /etc/tls-shunt-proxy/config.yaml (code=exited, status=1/FAILURE)
 Main PID: 7266 (code=exited, status=1/FAILURE)

Apr 07 13:50:52 vr.701227.xyz systemd[1]: tls-shunt-proxy.service: Main process exited, code=exited, status=1/FAILURE
Apr 07 13:50:52 vr.701227.xyz systemd[1]: tls-shunt-proxy.service: Failed with result 'exit-code'.
Apr 07 13:50:53 vr.701227.xyz systemd[1]: tls-shunt-proxy.service: Service RestartSec=1s expired, scheduling restart.
Apr 07 13:50:53 vr.701227.xyz systemd[1]: tls-shunt-proxy.service: Scheduled restart job, restart counter is at 5.
Apr 07 13:50:53 vr.701227.xyz systemd[1]: Stopped TLS Shunt Proxy Service.
Apr 07 13:50:53 vr.701227.xyz systemd[1]: tls-shunt-proxy.service: Start request repeated too quickly.
Apr 07 13:50:53 vr.701227.xyz systemd[1]: tls-shunt-proxy.service: Failed with result 'exit-code'.
Apr 07 13:50:53 vr.701227.xyz systemd[1]: Failed to start TLS Shunt Proxy Service.

**Comment by hedsbj** [comment]
tls-shunt-proxy.service - TLS Shunt Proxy Service
   Loaded: loaded (/etc/systemd/system/tls-shunt-proxy.service; disabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Tue 2020-04-07 15:36:59 CST; 621ms ago
     Docs: https://github.com/liberal-boy/tls-shunt-proxy/blob/master/README.md
  Process: 8323 ExecStart=/usr/local/bin/tls-shunt-proxy -config /etc/tls-shunt-proxy/config.yaml (code=exited, status=1/FAILURE)
 Main PID: 8323 (code=exited, status=1/FAILURE)

Apr 07 15:36:59 vr.701227.xyz systemd[1]: tls-shunt-proxy.service: Main process exited, code=exited, status=1/FAILURE
Apr 07 15:36:59 vr.701227.xyz systemd[1]: tls-shunt-proxy.service: Failed with result 'exit-code'.

**Comment by liberal-boy** [comment]
没有看到有用的日志，请使用命令运行
```shell
sudo -u tls-shunt-proxy /usr/local/bin/tls-shunt-proxy -config /etc/tls-shunt-proxy/config.yaml
```

**Comment by hedsbj** [comment]
显示 没有权限
2020/04/07 15:44:01 failed to read config /etc/tls-shunt-proxy/config.yaml: fail to load tls key pair for vr.701227.xyz: open /root/.acme.sh/vr.701227.xyz_ecc/fullchain.cer: permission denied

**Comment by liberal-boy** [comment]
那就是证书的权限问题，确保用户 `tls-shunt-proxy` 有权读取证书

**Comment by hedsbj** [comment]
多谢
